# Generated by Django 3.2 on 2022-06-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Адрес')),
                ('latitude', models.FloatField(verbose_name='Координаты широты')),
                ('longitude', models.FloatField(verbose_name='Координаты долготы')),
            ],
            options={
                'verbose_name': 'Адрес с координатами',
                'verbose_name_plural': 'Адреса с координатами',
            },
        ),
    ]
