# Generated by Django 3.2 on 2022-06-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Координаты широты'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Координаты долготы'),
        ),
    ]
