# Generated by Django 3.2 on 2022-05-28 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
