# Generated by Django 3.2 on 2022-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20220530_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'наличными'), ('online', 'электронно')], db_index=True, max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
