# Generated by Django 3.2 on 2022-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Необработан'), ('2', 'Подтвержден'), ('3', 'Готовится'), ('4', 'Доставляется'), ('5', 'Завершен'), ('6', 'Отменен')], db_index=True, default='Необработан', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
